language: python
dist: xenial

python:
  - 3.8
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - pipenv run flake8 .
  - pytest pypro --cov=pypro
after_success:
  - codecov
